jobs:
  build:
    docker:
      - image: docker:25.0-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t vul-ci-test:${CIRCLE_SHA1} .
      - run:
          name: Install vul
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/khulnasoft-lab/vul/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with vul (light)
          command: vul --exit-code 0 --no-progress vul-ci-test:${CIRCLE_SHA1}
workflows:
  version: 2
  release:
    jobs:
      - build
